### ISSUE TITLE
Opening Kate submenus causes menus to disappear

### ISSUE THREAD

**Issue by wmww** [canonical/mir#2324]
Repro: 
- Open Kate on Wayland
- Open a few submenus
- Eventually the main menu will disappear

Introduced somewhere between v2.5.0 and v2.6.0, I'll update this issue once I bisect down to a specific commit.

Kate running on XWayland is fine.

**Comment by wmww** [comment]
It would seem the primary mistake was not getting WLCS tests in place for all the things #1948 fixed. That will be rectified this time.

**Comment by wmww** [comment]
Looks like #1948 changed behavior from all Wayland popups getting keyboard focus to none getting it. That fixed #1818 and #1941, but introduced #2241. #2241 was fixed by #2241, which started giving keyboard focus to popups again, but only grabbing popups. This seems to be consistent with [the protocol](https://github.com/MirServer/mir/blob/45f08e9c35bacf36821944e01953809c8a1a3aca/src/wayland/protocol/xdg-shell.xml#L1085), however re-introduced #1818 and #1941. If anyone noticed this, they didn't do anything about it (probably because it's hard to keep track of what's a problem when the same bugs keep appearing and disappearing every other PR).

**Comment by wmww** [comment]
As for testing, a number of WLCS tests have been added or proposed for this stuff, including https://github.com/MirServer/wlcs/pull/216 which has been sitting unreviewed and https://github.com/MirServer/wlcs/pull/217, which I forgot to follow up on. There are also some tests that have landed but have been [marked as expected failures in Mir](https://github.com/MirServer/mir/blob/45f08e9c35bacf36821944e01953809c8a1a3aca/tests/acceptance-tests/wayland/CMakeLists.txt#L103).

The underlying problem with testing however is not the lack of it, things failing to land or tests being marked x-fail, it's that expected behavior keeps changing, so the tests have been just as volatile as Mir. We still don't know what doing the right thing is. The protocol seems to blatantly disagree with the observed behavior or Weston and Sway (thought further investigation may resolve this).

**Comment by wmww** [comment]
It appears Sway and Weston (and presumably GNOME, thought not yet tested) simply do not give keyboard focus to grabbing XDG popups, despite the protocol requiring it. [This](https://gitlab.freedesktop.org/wayland/weston/-/merge_requests/88) 3 year old (but with recent activity) open Weston PR seems to resolve that in Weston (which will presumably break Qt in weston just like it's broken for us).

Interestingly, it appeared that GNOME-terminal on sway was behaving as if it's popups were getting keyboard focus, and the reason for that was on my system the GNOME terminal server runs on XWayland. When I run it on Wayland the behavior changes.

Now we have an interesting moral dilemma: do we do the right thing, leaving Qt broken for the the foreseeable future, or do we maintain bug-compatibility with Qt and other compositors?

**Comment by AlanGriffiths** [comment]
> Now we have an interesting moral dilemma: do we do the right thing, leaving Qt broken for the the foreseeable future, or do we maintain bug-compatibility with Qt and other compositors?

How feasible would it be to have a "bug compatibility" configuration option at runtime?

In principle, the default behaviour should probably match the "reference compositor" (Weston). (I do realise that might be about to change.)
