### ISSUE TITLE
Events delivered late / inconsistently

### ISSUE THREAD

**Issue by Saviq** [canonical/mir#2698]
I'm going to put this under one issue, but it might actually be more underneath. There's a number of ways that makes me see something isn't correct when delivering input to clients. The common piece seems to be some seconds of inactivity of the user, followed by input that's not delivered consistently.

1. Some characters missing when I start typing after a short period of inactivity.
  That is often the first character, but may well be a couple subsequent ones
2. Mouse cursor only starts moving after a delay of some hundred milliseconds.
  It doesn't "catch up", rather the initial movement is lost
3. Scrolling misses the first few steps.
  This may well be the easiest to reproduce, as there's a small number of events, and it can't easily be blamed on PEBKAC.

Steps to reproduce 3.:
1. Move your cursor over a scrollable view.
2. Leave it be for 5 seconds.
3. Take care not to move the mouse.
4. Slowly scroll the mouse wheel one way or the other.

Expected:
1. Each scroll step results in the view scrolling.

Current:
1. Some events (I counted as much as 9) don't result in scrolling, after which they start to work correctly until a period of inactivity again.

I experience this on Miriway with Mir v2.10.0~rc1 and native clients right now, configured as follows:

```ini
x11-window-title=Miriway
idle-timeout=180
ctrl-alt=t:miriway-terminal # Default "terminal emulator finder"

display-config=static=/home/michal/.config/miriway.display
#display-config=single

shell-component=dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY
shell-component=swaybg -i /usr/share/backgrounds/warty-final-ubuntu.png
shell-component=mate-panel
shell-component=ubuntu-frame-osk
meta=a:mate-panel --run-dialog
ctrl-alt=t:mate-terminal

add-wayland-extensions=zwlr_layer_shell_v1

keymap=pl++compose:caps
```

```yaml
layouts:
  default:
    cards:
    - card-id: 0
      eDP-1:
        position: [1920, 0]
        scale: 1.5
      DisplayPort-1:
      HDMI-A-1:
```

This survives client as well as server restarting. I confirmed with `WAYLAND_DEBUG=1` that the missing events are not delivered to the clients.

**Comment by AlanGriffiths** [comment]
I've not been able to reproduce (yet)
