### ISSUE TITLE
Cursor from GDM Login remains on screen after logging into Miriway

### ISSUE THREAD

**Issue by mattkae** [canonical/mir#3198]
## Repro
- In GDM, put in your login credentials
- Move the cursor out of the text input if it is in there such that it is the default pointer
- Login
- Note that the cursor remains as a ghost on the desktop _forever_

## Environment
- Nvidia with Nouveau Drivers

**Comment by Saviq** [comment]
Wonder if related to #3206

**Comment by AlanGriffiths** [comment]
> Wonder if related to #3206

I don't see this with Miriway `edge/mir-pr3206`

**Comment by AlanGriffiths** [comment]
> (Now I have to work out why I hadn't noticed this before...)

Ah, so the the cursor isn't there _forever_ on Intel. It disappears after around 10s
