### ISSUE TITLE
Tons of screen tearing on my new rx 7800 xt GPU

### ISSUE THREAD

**Issue by mattkae** [canonical/mir#3327]
My eyes hurt :eyes: 

## Repro
- Boot into any mir-based compositor
- Open up a window that updates in any way whatsoever
- Watch as a big black bar flies across your screen on every update

On top of this, the entire experience is very laggy

[output.txt](https://github.com/canonical/mir/files/14950450/output.txt)

**Comment by mattkae** [comment]
This doesn't happen on any other compositor FYI (gnome, sway, kde, etc.)

**Comment by mattkae** [comment]
Another output where I was moving around a terminal on `miral-app` and seeing a ton of tearing:
[output.txt](https://github.com/canonical/mir/files/14951156/output.txt)

**Comment by mattkae** [comment]
This is a duplicate of https://github.com/canonical/mir/issues/2977 as it turns out

**Comment by AlanGriffiths** [comment]
@mattkae you could try Miriway `edge/pr94` which gets Mesa from 24.04 ([which Chris says works](https://github.com/canonical/mir/issues/2977#issuecomment-2051208341))
