### ISSUE TITLE
Provide `*.pc.in` files for mir platforms

### ISSUE THREAD

**Issue by mattkae** [canonical/mir#3352]
Recently in `miracle-wm`, we ran into this bug: https://github.com/mattkae/miracle-wm/issues/72

Spongy attempted to fix it with this pull request: https://github.com/mattkae/miracle-wm/pull/94, but @Conan-Kudo pointed out that this would be better solved if we could use `find_package` to check for the existence of mir platforms.

**Comment by Conan-Kudo** [comment]
It doesn't have to be `find_package()`, you can use [`pkg_get_variable()`](https://cmake.org/cmake/help/latest/module/FindPkgConfig.html#command:pkg_get_variable) to retrieve arbitrary variables from any pkgconfig file.

**Comment by mattkae** [comment]
That does indeed make sense @AlanGriffiths. _Perhaps_ the real issue is simply that the error message isn't helpful when you fail to resolve a platform. It doesn't give you any insight as to how to resolve the issue, but simply complains that it can't find some arbitrary directory.

A better solution would be to update this error message with actionable advice for the user. WDYT?

**Comment by AlanGriffiths** [comment]
> A better solution would be to update this error message with actionable advice for the user. WDYT?

#3353
