### ISSUE TITLE
Alt+` is confusing Firefox

### ISSUE THREAD

**Issue by AlanGriffiths** [canonical/mir#3379]
When I updated my Miriway snap to Mir trunk I discovered weirdness...

1. Open a couple of Firefox windows.
2. Alt-` between them
3. Move over a scrollable area and drag two fingers up/down

Expect: area scolls
Actual: Firefox revisits history

**Comment by AlanGriffiths** [comment]
Probably same as #3307, but happens consistently now

**Comment by mattkae** [comment]
Aha! you know what... I've seen this before in miracle-wm, but I couldn't quite put my finger on it: https://github.com/mattkae/miracle-wm/issues/42

**Comment by AlanGriffiths** [comment]
Fixed by #3382
