### ISSUE TITLE
Missing surface enter and leave events

### ISSUE THREAD

**Issue by wmww** [canonical/mir#342]
When a surface is mapped to a display, `wl_surface.enter` should be called, and `wl_surface.leave` should be called when it is no longer visible. There are currently no known bugs caused by this.

**Comment by AlanGriffiths** [comment]
@wmww please write a failing, disabled test

**Comment by wmww** [comment]
For the record, the WLCS PR that tests this is https://github.com/MirServer/wlcs/pull/148 and it's blocked on adding WLCS hooks for configuring outputs.

**Comment by AlanGriffiths** [comment]
# Notes to myself in 2024

* OutputManager - associated with the wl_display
* OutputManager::output_for() takes an output id and returns an OutputGlobal
* OutputGlobal - owned by OutputManager and associated with an output. This is the factory that binds a resource to an OutputInstance. (One instance per output per wayland socket)
* OutputInstance - this is the global (wl_output) published over Wayland to each client that binds this output. It is associated with an OutputGlobal which is associated with an output. (A client may, in principle, bind each output multiple times, so there can multiple of these)

So there's an OutputManager which has an OutputGlobal for each output, and zero or more OutputInstances for each client for each OutputGlobal

**Comment by Saviq** [comment]
Another pebble to this garden: changing scale live doesn't get applied even on a single output.
