### ISSUE TITLE
Our `fork`/`exec` spawning is unsafe

### ISSUE THREAD

**Issue by RAOF** [canonical/mir#3494]
`exec_wayland()` is called after `fork()`:
https://github.com/canonical/mir/blob/953de04e07444a8f4410dd2f044ad9d24fbec2ef/src/server/frontend_xwayland/xwayland_server.cpp#L53-L98

Unfortunately, `man 2 fork` says:

> After a fork() in a multithreaded program, the child can safely call only async-signal-safe functions (see signal-safety(7)) until such time as it calls execve(2).

We should instead do as much setup as possible in the parent, and *then* call `fork()`. (Amusingly, even `execvp` is not async-signal-safe :woman_facepalming: )

**Comment by AlanGriffiths** [comment]
> Amusingly, even `execvp` is not async-signal-safe

That probably doesn't matter: we should use `execve()` directly (we default `xwayland-path` to "/usr/bin/Xwayland", which doesn't need PATH handling)

**Comment by RAOF** [comment]
Oops! When reviewing https://github.com/canonical/mir/pull/3497 I also see that `miral::launch_app_env` suffers from the same problems.
