### ISSUE TITLE
Need to send `wp_fractional_scale_v1::preferred_scale` on live scale changes

### ISSUE THREAD

**Issue by Saviq** [canonical/mir#3552]
We're not sending `preferred_scale` when it's changed live.

Steps:
- run a Mir server with `--display-config=static=$PWD/foo.display`
- start a client supporting fractional scale and monitor for `preferred_scale`:
  `WAYLAND_DEBUG=1 gtk4-demo 2>&1 | grep preferred`
- modify the scale in the `foo.display` file

Expected:
- `preferred_scale` emitted for every change in scale

Current:
- `preferred_scale` only emitted once on client startup

**Comment by AlanGriffiths** [comment]
Writing it down before disappearing on vacation and forgetting it all...

`BasicSurface::track_outputs()` is the best place to track scale changes for each output

   * This currently simply tracks the outputs a surface intersects
   * But has access to the scale, so could track the scale and notify change

So, a plan:

1. `BasicSurface::track_outputs()` also tracks scale for each output (e.g. a map)
2. `BasicSurface::track_outputs()` sends a `scale_change_on_output(id, scale)` for tracked outputs with a new scale
3. Which needs `scale_change_on_output()` to `SurfaceObserver` family
4. That includes `WaylandSurfaceObserver` where `scale_change_on_output` calls
5. `WindowWlSurfaceRole::scale_change_on_output` which calls
6. `mf::FractionalScaleV1::scale_change_on_output` which sends the required notification

Although, that could (in theory) be inefficient if multiple outputs intersect a surface and all change scale at the same time. (Maybe I'll have a better idea when I get back)
