### ISSUE TITLE
Server Side Wayland Decorations Resize on Non-resizable Applications

### ISSUE THREAD

**Issue by tarek-y-ismail** [canonical/mir#3566]
## Steps to reproduce
1. Run a non-resizable application, making sure it uses its Wayland backend
2. Try dragging the corners or edges

**Expected behavior**: Decorations shouldn't resize. Additionally, the cursor shouldn't change.
**Current behavior**: The cursor indicates that edges and corners are resizable. And on dragging, decorations resize creating a blank area.

**Note**: This was confirmed on two SDL2 applications (neverputt, defendguin). It doesn't seem to occur on SDL3 examples (game-snake, camera-read-and-draw), so it might be SDL2 specific. Suggestions for/Reproductions on other non-SDL applications are welcome

**Comment by tarek-y-ismail** [comment]
After a bunch of investigation, it turns out that this was a bug with SDL2 not calling `xdg_toplevel::set_{min,max}_size` (see [bug report at sway](https://github.com/swaywm/sway/issues/4710) and [SDL fix PR](https://github.com/libsdl-org/SDL/pull/4065))

**Comment by Saviq** [comment]
> What's weird though is that GNOME somehow works around this? I'm not sure how or why.

Well, it's just that we treat no min/max size as unbounded, while GNOME treat it as if min/max was set to the preferred size? Or they've a quirk of some kind.

There's nothing in https://wayland.app/protocols/xdg-shell that I can see that would say which behaviour is appropriate - it's left to the compositor to decide, so IMO this bug can be closed on our side.
