### ISSUE TITLE
OSK doesn't play well with kiosk

### ISSUE THREAD

**Issue by tarek-y-ismail** [canonical/mir#3697]
At the moment, running [the electron iot example](https://github.com/canonical/iot-example-graphical-snap/tree/22/Electron-quick-start?tab=readme-ov-file) crashes on mir-kiosk if used in combination with ubuntu-frame-osk. WPE webkit doesn't crash, but the OSK draws a black rectangle over the area not covered by it.

A. Steps to reproduce with  iot example:
1. Launch mir-kiosk, the iot example, and ubunut-frame-osk
2. Click on any text or number field

Expected: OSK pops up, application works fine
Reality: OSK pops up at the top of the screen for a brief second, then the iot example crashes? with exit code 133

B. Steps to reproduce with WPE webkit:
1. Launch mir-kiosk, WPE webkit, and ubunut-frame-osk
2. Click on any text or number field

Expected: OSK pops up, application works fine
Reality: OSK pops up at the top of the screen, with the rest of the screen being covered by a black rectangle. Moving the cursor outside of the OSK causes the OSK to hide itself and the application renders normally.  This seems like a transparency issue?

**Comment by Saviq** [comment]
mir-kiosk never supported OSKs, wontfix.
