### ISSUE TITLE
Infrequent crash when layer shell client exits (uncleanly?)

### ISSUE THREAD

**Issue by Pajn** [canonical/mir#985]
While developing my panel, I frequently starts and stops it and sometimes it will crash. When this happens, very infrequently it will also take Mir down with it with the exception:
```
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::runtime_error> >'
  what():  Invalid session
```

I'll try to make a good reproduction example but thought I should post this so there's a record.

**Comment by wmww** [comment]
What version or git checkout of Mir?

**Comment by AlanGriffiths** [comment]
Is there a core file? A backtrace would be informative.

Also, looking at the places messages with this text are is thrown, it looks likely the window manager is referring to a session that does not exist. Are you running a server with your own window management policy? If so, can you reproduce with one of the Mir examples?

**Comment by AlanGriffiths** [comment]
Is this still an issue?

**Comment by AlanGriffiths** [comment]
> Is this still an issue?

I guess not
